# ==========================================
# SPRING BOOT APPLICATION CONFIGURATION
# Base configuration for all environments
# ==========================================

spring:
  application:
    name: eduplatform-backend
    version: ${APP_VERSION:0.0.1-SNAPSHOT}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:eduplatform_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: EduPlatformHikariPool

  # JPA Configuration
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  show-sql: false
  properties:
    hibernate:
      format_sql: true
      jdbc:
        batch_size: 25
      order_inserts: true
      order_updates: true

  # Flyway Migration - Disabled initially for easier development
  flyway:
    enabled: false # Change to true when you have migration files
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600s
      key-prefix: "eduplatform::"
      cache-null-values: false

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

  # Mail Configuration
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false # Set to false for development with Mailpit
          starttls:
            enable: false # Set to false for development

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always

# Application Specific Configuration
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
    expiration-ms: ${JWT_EXPIRATION:86400000} # 24 hours
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

---
# Development Environment Configuration
spring:
  config:
    activate:
      on-profile: development
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # Ensure this is set for development

---
# Production Environment Configuration
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true # Enable migrations in production
  mail:
    host: ${SMTP_HOST:smtp.yourprovider.com}
    port: ${SMTP_PORT:587}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  app:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://your-production-domain.com}
